#!/usr/bin/python
import re
class BuildingCounter:
    def count(self, count, p_type, isWeight):
        if p_type == 'address':
            count.addAddress()
        elif p_type == 'habitat':
            count.addHabitat()
        elif p_type == 'person':
            count.addPerson()
        elif p_type == 'education':
            count.addEducation(isWeight)
        elif p_type == 'religious':
            count.addReligious(isWeight)
        elif p_type == 'health':
            count.addHealth(isWeight)
        elif p_type == 'otherworkspace':
            count.addOtherWorkSpace()
        elif p_type == 'cospace':
            count.addCoSpace()
        elif p_type == 'government':
            count.addGovernment()
        elif p_type == 'hotel':
            count.addHotel(isWeight)
        elif p_type == 'factory':
            count.addFactory(isWeight)

class BuildingWeightChecker:
    pref = [
        ('โรงเรียน', 'education'),
        ('โรงเรีนย', 'education'),
        ('โรงเรัยน', 'education'),
        ('รร', 'education'),
        ('ร.ร.', 'education'),
        ('มหาวิทยาลัย', 'education'),
        ('มหาลัย', 'education'),
        ('วิทยาลัย', 'education'),
        ('ศูนย์พัฒนาเด็ก', 'education'),
        ('ศูนย์เด็ก', 'education'),
        ('ศูนย์เด็', 'education'),
        ('สำนักการสาธารณสุข', 'health'),
        ('อนามัย', 'health'),
        ('รพ', 'health'),
        ('โรงพยาบาล', 'health'),
        ('โรงแรม', 'hotel'),
        ('โรงเเรม', 'hotel'),
        ('โฮมสเ', 'hotel'),
        ('รีสอร์', 'hotel'),
        ('วัด', 'religious'),
        ('วัก', 'religious'),
        ('คริส', 'religious'),
        ('สำนักสงฆ์', 'religious'),
        ('มัสยิส', 'religious'),
        ('มัสยิด', 'religious'),
        ('สุเหร่า', 'religious'),
        ('ตาดีกา', 'religious'),
        ('โรงกำเนิด', 'factory'),
        ('โรงงาน', 'factory'),
        ('โรงาน', 'factory'),
        ('โรงไม้', 'factory'),
        ('โรงพิมพ์', 'factory'),
        ('โรงกลึง', 'factory'),
        ('โรงขนม', 'factory'),
        ('โรงแป้ง', 'factory'),
        ('โรงข้าวปุ้น', 'factory'),
        ('โรงอบ', 'factory'),
        ('โรงบด', 'factory'),
        ('โรงปั่น', 'factory'),
        ('โรงตาก', 'factory'),
        ('โรงหมัก', 'factory'),
        ('โรงคัด', 'factory'),
        ('น้ำแข็ง', 'factory'),
        ('โรงน้ำแข็ง', 'factory'),
        ('โรงหลอม', 'factory'),
        ('โรงหีบ', 'factory'),
        ('โรงทำ', 'factory'),
        ('โรงสี', 'factory'),
        ('โรงน้ำ', 'factory'),
        ('โรงนำ้', 'factory'),
        ('โรงบรรจุ', 'factory'),
        ('โรงเย็น', 'factory'),
        ('โรงกลั่น', 'factory'),
        ('โรงหล่อ', 'factory'),
        ('โรงช่าง', 'factory'),
        ('โรงแต่ง', 'factory'),
        ('โรงกำจัด', 'factory'),
        ('โรงบำบัด', 'factory'),
        ('โรงอบ', 'factory'),
        ('โรงเย็บ', 'factory'),
        ('โรงเชือด', 'factory'),
        ('โรงฆ่า', 'factory'),
        ('โรงไหม', 'factory'),
        ('โรงแช่เย็น', 'factory'),
        ('โรงทอ', 'factory'),
    ]
    
    postf = [
        ('สาธรณสุข', 'health'),
        ('คลินิค', 'health'),
        ('คลินิก', 'health'),
        ('อพาร์ทเม้นท์', 'habitat'),
        ('วิลเลจ', 'habitat'),
        ('โฮเทล', 'hotel'),
        ('บูติก', 'hotel'),
        ('อินน์', 'hotel'),
        ('เฮาส์', 'hotel'),
        ('โฮเต็ล', 'hotel'),
        ('บังกะโล', 'hotel'),
        ('โรงแรม', 'hotel'),
        ('รีสอร์ท', 'hotel'),
        ('เพลส', 'hotel')
    ]

    # for p in pref:
    #     if(word.startswith(p[0])):
    #         print(p[1])

    def isBuildingWeight(self, word):
        pre = False
        post = False
        for p in BuildingWeightChecker.pref:
            if(str(word).startswith(str(p[0]))):
                pre = True
        for p in BuildingWeightChecker.postf:
            if(str(word).endswith(str(p[0]))):
                post = True
        return (pre or post)

    
class BuildingClassify:
    corpus = [
        ('เลขที่', 'address'),
        ('เลขห้อง', 'address'),
        ('บ้านเลขที่', 'address'),
        ('นาย', 'person'),
        ('นาง', 'person'),
        ('ปู่', 'person'),
        ('ย่า', 'person'),
        ('ตา', 'person'),
        ('ยาย', 'person'),
        ('นส.', 'person'),
        ('น.ส.', 'person'),
        ('แม่', 'person'),
        ('พ่อ', 'person'),
        ('คุณ', 'person'),
        ('ป้า', 'person'),
        ('ลุง', 'person'),
        ('พี่', 'person'),
        ('น้อง', 'person'),
        ('เถ้าแก่', 'person'),
        ('ผู้ช่วย', 'person'),
        ('กำนัน', 'person'),
        ('ผู้ใหญ่บ้าน', 'person'),
        ('ดร.', 'person'),
        ('ผอ.', 'person'),
        ('ผช.', 'person'),
        ('ครู', 'person'),
        ('หมอ', 'person'),
        ('ทนาย', 'person'),
        ('ผู้บริหาร', 'person'),
        ('อสม', 'person'),
        ('กัมพูชา', 'person'),
        ('พม่า', 'person'),
        ('องค์การบริหาร', 'otherworkspace'),
        ('อบต', 'otherworkspace'),
        ('อบจ', 'otherworkspace'),
        ('ที่ว่าการ', 'otherworkspace'),
        ('เทศบาล', 'otherworkspace'),
        ('ที่ทำการ', 'otherworkspace'),
        ('กองร้อย', 'otherworkspace'),
        ('เรือนจำ', 'otherworkspace'),
        ('หมวดบำรุง', 'otherworkspace'),
        ('กองบังชาการ', 'otherworkspace'),
        ('พระตำหนัก', 'otherworkspace'),
        ('อุทยานแห่งชาติ', 'otherworkspace'),
        ('สถาบันการเงิน', 'otherworkspace'),
        ('อปพร', 'habitat'),
        ('ซอย', 'habitat'),
        ('บ.', 'habitat'),
        ('บ้านพัก', 'habitat'),
        ('พักอาศัย', 'habitat'),
        ('บ้านเลข', 'habitat'),
        ('บ้านเช่า', 'habitat'),
        ('ห้องพัก', 'habitat'),
        ('ตึกพัก', 'habitat'),
        ('หอพัก', 'habitat'),
        ('หอนิสิต', 'habitat'),
        ('หอนักศึกษา', 'habitat'),
        ('ห้องเบอร์', 'habitat'),
        ('ที่พักระหว่างทาง', 'cospace'),
        ('ที่พักขยะติดเชื้อ', 'health'),
        ('ที่พักขยะ', 'cospace'),
        ('หอหญิง', 'habitat'),
        ('หอชาย', 'habitat'),
        ('ชุมชน', 'habitat'),
        ('ให้เช่า', 'habitat'),
        ('หมู่บ้าน', 'habitat'),
        ('เลขที่', 'habitat'),
        ('คอนโด', 'habitat'),
        ('พักคนงาน', 'habitat'),
        ('อพาร์ทเม้นท์', 'habitat'),
        ('วิลเลจ', 'habitat'),
        ('ที่พัก', 'habitat'),
        ('ห้องเช่า', 'habitat'),
        ('ห้องแถว', 'habitat'),
        ('โรงนอน', 'habitat'),
        ('แคมป์', 'habitat'),
        ('แคมคนงาน', 'habitat'),
        ('ไม่ทราบ', 'habitat'),
        ('ไม่มีบ้านเลขที่', 'habitat'),
        ('ไม่มีเลขที่', 'habitat'),
        ('โรงเรือน', 'habitat'),
        ('เรือน', 'habitat'),
        ('เรือนพัก', 'habitat'),
        ('บ้าน', 'habitat'),
        ('หมู่', 'habitat'),
        ('แฟลต', 'habitat'),
        ('แฟต', 'habitat'),
        ('เเฟรช', 'habitat'),
        ('แมนชั่น', 'habitat'),
        ('เคหะ', 'habitat'),
        ('ซุ้มไก่', 'habitat'),
        ('คอนโด', 'habitat'),
        ('คอกสัตว์', 'habitat'),
        ('คอกวัว', 'habitat'),
        ('คอกไก่', 'habitat'),
        ('คอกหมู', 'habitat'),
        ('กรงสัตว์', 'habitat'),
        ('ตำรวจชุมชน', 'habitat'),
        ('บ้านพักครู', 'education'),
        ('พักครู', 'education'),
        ('กศน', 'education'),
        ('เรียน', 'education'),
        ('ทยานุกูล', 'education'),
        ('พิทยา', 'education'),
        ('โรงเรียน', 'education'),
        ('โรงเรีนย', 'education'),
        ('โรงเรัยน', 'education'),
        ('โรงเนียน', 'education'),
        ('รร ', 'education'),
        ('รร.', 'education'),
        ('ร.ร.', 'education'),
        ('ป.1', 'education'),
        ('ป.2', 'education'),
        ('ป.3', 'education'),
        ('ป.4', 'education'),
        ('ป.5', 'education'),
        ('ป.6', 'education'),
        ('ศพด', 'education'),
        ('มหาวิทยาลัย', 'education'),
        ('ทยาคาร', 'education'),
        ('ทยาคม', 'education'),
        ('มหาลัย', 'education'),
        ('วิทยาลัย', 'education'),
        ('อาหารเด็ก', 'education'),
        ('บ้านเด็ก', 'education'),
        ('พัฒนาเด', 'education'),
        ('ศูนย์พัฒนาเด็ก', 'education'),
        ('ดุริยางค์', 'education'),
        ('ลูกเสือ', 'education'),
        ('ศูนย์เด็ก', 'education'),
        ('ศูนย์เด', 'education'),
        ('คณะเทคโน', 'education'),
        ('สุขศึกษา', 'education'),
        ('เทคโน', 'education'),
        ('คณะมนุษย์', 'education'),
        ('คณะวิทยาศาสตร์', 'education'),
        ('หมวดพลานามัย', 'education'),
        ('การงานอาชีพ', 'education'),
        ('ปัจฉิม', 'education'),
        ('พิพิธภัณ์', 'education'),
        ('ศูนย์เรียนรู้', 'education'),
        ('ศึกษา', 'education'),
        ('งานการอาชีพ', 'education'),
        ('อนุบาล', 'education'),
        ('คอมพิวเตอร์', 'education'),
        ('ครุศาสตร์', 'education'),
        ('เรือนดนตรี', 'education'),
        ('เรือนศิลป์', 'education'),
        ('สปช', 'education'),
        ('พละศึกษา', 'education'),
        ('อาคารพละ', 'education'),
        ('ภาษา', 'education'),
        ('ศิลปะ', 'education'),
        ('อบรม', 'education'),
        ('อาคารเรียน', 'education'),
        ('การเรียน', 'education'),
        ('นักเรียน', 'education'),
        ('ห้องสมุด', 'education'),
        ('หอสมุด', 'education'),
        ('ห้องพักครู', 'education'),
        ('การศึกษา', 'education'),
        ('ศูนย์พัฒนา', 'education'),
        ('ศูนย์ฯเด็ก', 'education'),
        ('เด็กเล็ก', 'education'),
        ('ประถมศึกษา', 'education'),
        ('ประถม', 'education'),
        ('ประถมวัย', 'education'),
        ('มัธยมศึกษา', 'education'),
        ('ม.ต้น', 'education'),
        ('มัธยม', 'education'),
        ('ม.ปลาย', 'education'),
        ('คหกรรม', 'education'),
        ('ชอปอุสาหกรรม', 'education'),
        ('แผนกโลหะ', 'education'),
        ('แผนกอิเล็ก', 'education'),
        ('แผนกเทคนิค', 'education'),
        ('คหะกรรม', 'education'),
        ('วิทยาลัย', 'education'),
        ('อ่านหนังสือ', 'education'),
        ('พัฒนาเด็ก', 'education'),
        ('ปฐมวัย', 'education'),
        ('ศูนย์เด็ก', 'education'),
        ('เลี้ยงเด็ก', 'education'),
        ('วิชา', 'education'),
        ('แนะแนว', 'education'),
        ('ภาควิชา', 'education'),
        ('วิชาเคมี', 'education'),
        ('วิชาการ', 'education'),
        ('ฝ่ายปกครอง', 'education'),
        ('ผู้ปกครอง', 'education'),
        ('พลศึกษา', 'education'),
        ('พละศึกษา', 'education'),
        ('ชีววิทยา', 'education'),
        ('วิทยาศาสตร์', 'education'),
        ('ICT', 'education'),
        ('English', 'education'),
        ('วิทยาการ', 'education'),
        ('วิทยบริการ', 'education'),
        ('อนุบาล', 'education'),
        ('นักการ', 'education'),
        ('ภารโรง', 'education'),
        ('กศน', 'education'),
        ('ทัศนศิลป์', 'education'),
        ('ดนตรีไทย', 'education'),
        ('ดนตรีสากล', 'education'),
        ('พิพิธภัณฑ์', 'education'),
        ('พิพิธภัณ์', 'education'),
        ('ศูยน์วัฒนธรรม', 'education'),
        ('ศูนย์วัฒนธรรม', 'education'),
        ('สาระสนเทศ', 'education'),
        ('ศูนย์ส่งเสริม', 'education'),
        ('คณิต', 'education'),
        ('ดนตรี', 'education'),
        ('วิทย์', 'education'),
        ('ศิลป์', 'education'),
        ('สังคม', 'education'),
        ('สำนักการสาธารณสุข', 'health'),
        ('รพ ', 'health'),
        ('รพ สต', 'health'),
        ('รพ.', 'health'),
        ('รพสต', 'health'),
        ('รพ.สต.', 'health'),
        ('.สต.', 'health'),
        ('อนามัย', 'health'),
        ('สสอ', 'health'),
        ('สสจ', 'health'),
        ('สตม', 'health'),
        ('โรงพยาบาล', 'health'),
        ('สอ.', 'health'),
        ('ศสมช', 'health'),
        ('ศตม', 'health'),
        ('สาธารณสุข', 'health'),
        ('แม่และเด็ก', 'health'),
        ('ward', 'health'),
        ('พยาบาล', 'health'),
        ('เภสัช', 'health'),
        ('แพทย', 'health'),
        ('เวชภัณฑ์', 'health'),
        ('เวชระเบียน', 'health'),
        ('ระเบียน', 'health'),
        ('ห้องทำบัตร', 'health'),
        ('ผป', 'health'),
        ('ผู้ป่วย', 'health'),
        ('ผู้ป้วย', 'health'),
        ('ผู้ปวย', 'health'),
        ('ผู้ป่', 'health'),
        ('ผู้สูงอายุ', 'health'),
        ('สูงอายุ', 'health'),
        ('อุบัติเหตุ', 'health'),
        ('อายุร', 'health'),
        ('อายุชาย', 'health'),
        ('อายุหญิง', 'health'),
        ('วัณโรค', 'health'),
        ('กลุ่มเวช', 'health'),
        ('กุมารเวช', 'health'),
        ('นารีเวช', 'health'),
        ('ฝ่ายเวช', 'health'),
        ('เวชศาสตร์', 'health'),
        ('ฟื้นฟู', 'health'),
        ('นิติเวช', 'health'),
        ('จักษุ', 'health'),
        ('ห้องคลอด', 'health'),
        ('คลอด', 'health'),
        ('ผ่าตัด', 'health'),
        ('ตรวจภายใน', 'health'),
        ('สุขาภิบาล', 'health'),
        ('ชันสูตร', 'health'),
        ('กายอุปกรณ์', 'health'),
        ('ฝังเข็ม', 'health'),
        ('คุมกำเนิด', 'health'),
        ('เอ็กซเรย์', 'health'),
        ('เอกซ์เรย์', 'health'),
        ('เอ็กเรย์', 'health'),
        ('เอกเรย์', 'health'),
        ('พิเศษ', 'health'),
        ('พิเศษรวม', 'health'),
        ('ห้องพิเศษ', 'health'),
        ('ตึกสงฆ์', 'health'),
        ('ตึกพิเศษ', 'health'),
        ('ตึกเด็ก', 'health'),
        ('พิเศษเด็ก', 'health'),
        ('เด็กพิเศษ', 'health'),
        ('พัฒนาการเด็ก', 'health'),
        ('ธนาคารเลือด', 'health'),
        ('ประกันสังคม', 'health'),
        ('จ่ายกลาง', 'health'),
        ('ปฐมภูมิ', 'health'),
        ('ทุติยภูมิ', 'health'),
        ('ขาเทียม', 'health'),
        ('opd', 'health'),
        ('OPD', 'health'),
        ('ipd', 'health'),
        ('IPD', 'health'),
        ('PCU', 'health'),
        ('pcu', 'health'),
        ('NCD', 'health'),
        (' er', 'health'),
        ('ER', 'health'),
        ('LAB', 'health'),
        ('Lab', 'health'),
        ('lab', 'health'),
        ('OR', 'health'),
        ('LR', 'health'),
        ('ICN', 'health'),
        ('ICU', 'health'),
        ('icn', 'health'),
        ('icu', 'health'),
        ('care', 'health'),
        ('EMS', 'health'),
        ('เอ็มอาร์ไอ', 'health'),
        ('กึ่งวิกฤต', 'health'),
        ('ตึกบำบัด', 'health'),
        ('พักญาติ', 'health'),
        ('พักญาติ', 'health'),
        ('อายุรกรรม', 'health'),
        ('อายุกรรม', 'health'),
        ('สูตินารี', 'health'),
        ('สูตินารี', 'health'),
        ('ครรภ์', 'health'),
        ('แรกเกิด', 'health'),
        ('ผิวหนัง', 'health'),
        ('ทันตะ', 'health'),
        ('อาคารรักษา', 'health'),
        ('บำบัดรักษา', 'health'),
        ('ตรวจรักษา', 'health'),
        ('จมูก', 'health'),
        ('ทางเดินหายใจ', 'health'),
        ('ตึกเวช', 'health'),
        ('เวชศาตร์', 'health'),
        ('เภสัช', 'health'),
        ('มะเร็ง', 'health'),
        ('ป่วย', 'health'),
        ('x-ray', 'health'),
        ('xray', 'health'),
        ('X ray', 'health'),
        ('Xray', 'health'),
        ('X-RAY', 'health'),
        ('X-ray', 'health'),
        ('รังสี', 'health'),
        ('เฉพาะทาง', 'health'),
        ('โลหิต', 'health'),
        ('เอกซเรย์', 'health'),
        ('ทันตกรรม', 'health'),
        ('ไตเทียม', 'health'),
        ('ตึกไต', 'health'),
        ('ศูนย์ไต', 'health'),
        ('โรคไต', 'health'),
        ('ประสาท', 'health'),
        ('เบาหวาน', 'health'),
        ('ความดัน', 'health'),
        ('โภชนาการ', 'health'),
        ('บำบัดยาเสพติด', 'health'),
        ('กายภาพบำบัด', 'health'),
        ('กายภาพ', 'health'),
        ('แพทย์แผนไทย', 'health'),
        ('นักศึกษาเเพทย์', 'health'),
        ('แผนไทย', 'health'),
        ('เเผนไทย', 'health'),
        ('ศูนย์เปล', 'health'),
        ('ห้องยา', 'health'),
        ('คลังยา', 'health'),
        ('จ่ายยา', 'health'),
        ('คลังยา', 'health'),
        ('ศัลย', 'health'),
        ('ศัลย์', 'health'),
        ('ศัลยกรรม', 'health'),
        ('ศัลกรรม', 'health'),
        ('กระดูก', 'health'),
        ('ตรวจตา', 'health'),
        ('บริการไต', 'health'),
        ('เวชกรรม', 'health'),
        ('โรคเรื้อรัง', 'health'),
        ('ส่องกล้อง', 'health'),
        ('เอดส์', 'health'),
        ('เคมีบำบัด', 'health'),
        ('สุขภาพ', 'health'),
        ('อุบัติเหตุ', 'health'),
        ('กู้ชีพ', 'health'),
        ('ตึกฉุกเฉิน', 'health'),
        ('สถานบริการ', 'health'),
        ('โภชนศาสตร์', 'health'),
        ('สหวิชาชีพ', 'health'),
        ('สังคมสงเคราะห์', 'health'),
        ('ฉุกเฉิน', 'health'),
        ('ส่งต่อ', 'health'),
        ('คัดกรอง', 'health'),
        ('งานเวช', 'health'),
        ('เวชศาสตร์', 'health'),
        ('เวชปฏิบัติ', 'health'),
        ('เก็บศพ', 'health'),
        ('โกดังเก็บศพ', 'health'),
        ('โอพีดี', 'health'),
        ('พยาธิวิทยา', 'health'),
        ('กาชาด', 'health'),
        ('ตรวจโรค', 'health'),
        ('คลีนิค', 'health'),
        ('คลีนิก', 'health'),
        ('คลินิก', 'health'),
        ('คลินิค', 'health'),
        ('สูติกรรม', 'health'),
        ('ห้องดับจิต', 'health'),
        ('พักศพ', 'health'),
        ('ห้องพักศพ', 'health'),
        ('ที่พักศพ', 'health'),
        ('สูติ', 'health'),
        ('กีฏ', 'health'),
        ('โรค', 'health'),
        ('ห้องแลบ', 'health'),
        ('ห้องแลป', 'health'),
        ('ศูนย์แลป', 'health'),
        ('ซักฟอก', 'health'),
        ('ชักฟอก', 'health'),
        ('จิตเวช', 'health'),
        ('ระบาดวิทยา', 'health'),
        ('ศตม', 'health'),
        ('สสจ', 'health'),
        ('นคม', 'health'),
        ('สมเด็จพระยุพราช', 'health'),
        ('สคร', 'health'),
        ('ติดเชื้อ', 'health'),
        ('โรงแรม', 'hotel'),
        ('โรงเเรม', 'hotel'),
        ('รีสอร์ท', 'hotel'),
        ('โฮเทล', 'hotel'),
        ('อินน์', 'hotel'),
        ('โฮม', 'hotel'),
        ('เฮาส์', 'hotel'),
        ('โฮเต็ล', 'hotel'),
        ('รีสอร์ต', 'hotel'),
        ('เพลส', 'hotel'),
        ('hotel', 'hotel'),
        ('โฮสเทล', 'hotel'),
        ('โฮเทล', 'hotel'),
        ('โฮมสเต', 'hotel'),
        ('โอมสเต', 'hotel'),
        ('bar', 'hotel'),
        ('Lobby', 'hotel'),
        ('lobby', 'hotel'),
        ('Hotel', 'hotel'),
        ('hotel', 'hotel'),
        ('hutch', 'hotel'),
        ('รอยัลปาร์ค', 'hotel'),
        ('จัดเลี้ยง', 'hotel'),
        ('บีช', 'hotel'),
        ('บูติก', 'hotel'),
        ('บังกะโล', 'hotel'),
        ('ฮัท', 'hotel'),
        ('เฮ้าส์', 'hotel'),
        ('วัด', 'religious'),
        ('เวฬุวัน', 'religious'),
        ('อาราม', 'religious'),
        ('คริส', 'religious'),
        ('พำนักสง', 'religious'),
        ('เก็บกระดูก', 'religious'),
        ('สำนักสงฆ์', 'religious'),
        ('พระประธาน', 'religious'),
        ('วิทยาทาน', 'religious'),
        ('มณฑบ', 'religious'),
        ('มณฑป', 'religious'),
        ('สุเหร่า', 'religious'),
        ('ตาดีกา', 'religious'),
        ('มัสยิด', 'religious'),
        ('เจดี', 'religious'),
        ('บิณฑบาตร', 'religious'),
        ('บิณฑบาต', 'religious'),
        ('นั่งสมาธิ', 'religious'),
        ('วิหาร', 'religious'),
        ('กุฏิ', 'religious'),
        ('กฎิ', 'religious'),
        ('กุฎี', 'religious'),
        ('กุฏ', 'religious'),
        ('กุฎ', 'religious'),
        ('กูฏ', 'religious'),
        ('กูฎ', 'religious'),
        ('กุฦิ', 'religious'),
        ('ฏิพระ', 'religious'),
        ('เมรุ', 'religious'),
        ('โกศ', 'religious'),
        ('โกฏ', 'religious'),
        ('อัฐิ', 'religious'),
        ('ฌาปนสถาน', 'religious'),
        ('ซุ้มระฆัง', 'religious'),
        ('วิปัสนา', 'religious'),
        ('ซุ้มพระ', 'religious'),
        ('พระญาณ', 'religious'),
        ('พระพรหม', 'religious'),
        ('พระเทศ', 'religious'),
        ('อุโบสถ', 'religious'),
        ('คำภีร์', 'religious'),
        ('น้ำมนต์', 'religious'),
        ('ปริยธรรม', 'religious'),
        ('ปริยัติธรรม', 'religious'),
        ('โบสถ์', 'religious'),
        ('โบถ์ส', 'religious'),
        ('โบสถ', 'religious'),
        ('โบรส์', 'religious'),
        ('วัด', 'religious'),
        ('วัก', 'religious'),
        ('ลานวัด', 'religious'),
        ('พระธาตุ', 'religious'),
        ('พระสังฆราช', 'religious'),
        ('องค์พระ', 'religious'),
        ('แม่ชี', 'religious'),
        ('สังฆทาน', 'religious'),
        ('มณฑป', 'religious'),
        ('ศาลาธรรม', 'religious'),
        ('ศาลาสวด', 'religious'),
        ('ศาลาพักศพ', 'religious'),
        ('โรงทึม', 'religious'),
        ('ศาลาไว้ศพ', 'religious'),
        ('สวดศพ', 'religious'),
        ('วางศพ', 'religious'),
        ('บำเพ็ญบุญ', 'religious'),
        ('การเปรียญ', 'religious'),
        ('การเปรียณ', 'religious'),
        ('การเปรียน', 'religious'),
        ('ศาลาบำเพ็ญกุศล', 'religious'),
        ('ลานบุญ', 'religious'),
        ('ศาลตะเคียน', 'religious'),
        ('ศาลเจ้า', 'religious'),
        ('ศาลพ่อ', 'religious'),
        ('ศาลแม่', 'religious'),
        ('ศาลปู่', 'religious'),
        ('ศาลย่า', 'religious'),
        ('ศาลตา', 'religious'),
        ('ศาลยาย', 'religious'),
        ('ศาลหลักเมือง', 'religious'),
        ('โรงธรรม', 'religious'),
        ('ปฏิบัติธรรม', 'religious'),
        ('โรงทาน', 'religious'),
        ('โรงฉัน', 'religious'),
        ('โรวฉัน', 'religious'),
        ('กุฎิสงฆ์', 'religious'),
        ('ศาวนา', 'religious'),
        ('พระพุทธ', 'religious'),
        ('พระพุทธศาสนา', 'religious'),
        ('ฐานพระ', 'religious'),
        ('สวดมนต์', 'religious'),
        ('ไตรภาคี', 'religious'),
        ('พุทธสถาน', 'religious'),
        ('ศาสน', 'religious'),
        ('บาทหลวง', 'religious'),
        ('พระไตรปิฎก', 'religious'),
        ('พระครู', 'religious'),
        ('หอฉัน', 'religious'),
        ('หอระฆัง', 'religious'),
        ('สถูป', 'religious'),
        ('สธูป', 'religious'),
        ('สังฆาวาส', 'religious'),
        ('หลวงพ่อ', 'religious'),
        ('สงฆ์', 'religious'),
        ('เจ้าอาวาส', 'religious'),
        ('ที่พักสงฆ์', 'religious'),
        ('หอพระ', 'religious'),
        ('หอไตร', 'religious'),
        ('หอคัมภี', 'religious'),
        ('พุทธทาส', 'religious'),
        ('พุทธมณฑล', 'religious'),
        ('ปฏิบัติธรรม', 'religious'),
        ('บูชา', 'religious'),
        ('วัตถุมงคล', 'religious'),
        ('หอฉัตร', 'religious'),
        ('ละหมาด', 'religious'),
        ('ตำหนักพระ', 'religious'),
        ('ซ่อมรถ', 'factory'),
        ('โกดัง', 'factory'),
        ('โรงกำเนิด', 'factory'),
        ('โรงงาน', 'factory'),
        ('โรงาน', 'factory'),
        ('โรงไม้', 'factory'),
        ('โรงพิมพ์', 'factory'),
        ('โรงกลึง', 'factory'),
        ('ปั้มนำ้มัน', 'factory'),
        ('ห้องเครื่อง', 'factory'),
        ('โรงขนม', 'factory'),
        ('โรงแป้ง', 'factory'),
        ('โรงข้าวปุ้น', 'factory'),
        ('โรงอบ', 'factory'),
        ('โรงบด', 'factory'),
        ('โรงปั่น', 'factory'),
        ('โรงตาก', 'factory'),
        ('โรงหมัก', 'factory'),
        ('โรงคัด', 'factory'),
        ('โรงแกะ', 'factory'),
        ('โรงน้ำแข็ง', 'factory'),
        ('น้ำแข็ง', 'factory'),
        ('โรงหลอม', 'factory'),
        ('โรงหีบ', 'factory'),
        ('โรงทำ', 'factory'),
        ('อู่', 'factory'),
        ('การช่าง', 'factory'),
        ('เซรามิค', 'factory'),
        ('คอนกรีต', 'factory'),
        ('ผลิต', 'factory'),
        ('โรงสี', 'factory'),
        ('โรงน้ำ', 'factory'),
        ('โรงนำ้', 'factory'),
        ('โรงบรรจุ', 'factory'),
        ('อุตสาหกรรม', 'factory'),
        ('อลูมิเนี', 'factory'),
        ('โรงเย็น', 'factory'),
        ('โรงกลั่น', 'factory'),
        ('โรงหล่อ', 'factory'),
        ('หัตถกรรม', 'factory'),
        ('แปรรูป', 'factory'),
        ('ฟาร์ม', 'factory'),
        ('คลัง', 'factory'),
        ('ประกันคุณภาพ', 'factory'),
        ('สินค้า', 'factory'),
        ('เครื่องกำเนิด', 'factory'),
        ('ห้องอบสี', 'factory'),
        ('โรงช่าง', 'factory'),
        ('การยาง', 'factory'),
        ('โลหะกิจ', 'factory'),
        ('คุณภาพ', 'factory'),
        ('สูบน้ำ', 'factory'),
        ('เฟอร์นิเจอร์', 'factory'),
        ('โรงแต่ง', 'factory'),
        ('บ่อบำบัด', 'factory'),
        ('โรงกำจัด', 'factory'),
        ('โรงบำบัด', 'factory'),
        ('โรงบำบัด', 'factory'),
        ('ตัดเย็บ', 'factory'),
        ('เย็บผ้า', 'factory'),
        ('เย็บเสื้อผ้า', 'factory'),
        ('โรงเชือด', 'factory'),
        ('โรงฆ่า', 'factory'),
        ('โรงไหม', 'factory'),
        ('รีไซเคิล', 'factory'),
        ('โรงแช่เย็น', 'factory'),
        ('โรงทอผ้า', 'factory'),
        ('โรงเผา', 'factory'),
        ('เทคโนโลยี', 'factory'),
        ('การไฟฟ้า', 'factory'),
        ('โรงไฟฟ้า', 'factory'),
        ('กำเนิดไฟฟ้า', 'factory'),
        ('โรงสูบ', 'factory'),
        ('รง.', 'factory'),
        ('ห้อง', 'cospace'),
        ('น้ำดื่ม', 'cospace'),
        ('ห้องพยาบาล', 'cospace'),
        ('ปฐมพยาบาล', 'cospace'),
        ('บำบัดน้ำเสีย', 'cospace'),
        ('ลานพระ', 'cospace'),
        ('หอประชุม', 'cospace'),
        ('ห้องประชุม', 'cospace'),
        ('อาหาร', 'cospace'),
        ('โรงอาหาร', 'cospace'),
        ('โรงอาห', 'cospace'),
        ('โรวอาหาร', 'cospace'),
        ('ห้องอาหาร', 'cospace'),
        ('ศูนย์อาหาร', 'cospace'),
        ('ห้องครัว', 'cospace'),
        ('ประกอบอาหาร', 'cospace'),
        ('ประกอบเลี้ยง', 'cospace'),
        ('เครื่องครัว', 'cospace'),
        ('โรงครัว', 'cospace'),
        ('รับแขก', 'cospace'),
        ('ห้องน้ำ', 'cospace'),
        ('โรงยิม', 'cospace'),
        ('สระว่ายน้ำ', 'cospace'),
        ('เสาธง', 'cospace'),
        ('ลานจอดรถ', 'cospace'),
        ('ลานเยาวชน', 'cospace'),
        ('สวน', 'cospace'),
        ('เด็กเล่น', 'cospace'),
        ('สนาม', 'cospace'),
        ('ศาลาพัก', 'cospace'),
        ('โรงเก็บรถ', 'cospace'),
        ('ป้อมยาม', 'cospace'),
        ('ตู้ยาม', 'cospace'),
        ('รปภ', 'cospace'),
        ('ป้าย', 'cospace'),
        ('ขยะ', 'cospace'),
        ('hall', 'cospace'),
        ('มอเตอร์', 'cospace'),
        ('ออกกำลัง', 'cospace'),
        ('โรงเก็บ', 'cospace'),
        ('เก็บของ', 'cospace'),
        ('ห้องเก็บ', 'cospace'),
        ('ประชุม', 'cospace'),
        ('สนันสนุน', 'cospace'),
        ('เอนกประสงค์', 'cospace'),
        ('อเนกประสงค์', 'cospace'),
        ('กำแพง', 'cospace'),
        ('สุขา', 'cospace'),
        ('จอดรถ', 'cospace'),
        ('โรงรถ', 'cospace'),
        ('ประชาคม', 'cospace'),
        ('สโมสร', 'cospace'),
        ('ล้างมือ', 'cospace'),
        ('ที่รกร้าง', 'cospace'),
        ('ที่ว่าง', 'cospace'),
        ('พท.ว่าง', 'cospace'),
        ('โรงเลี้ยง', 'cospace'),
        ('ซักล้าง', 'cospace'),
        ('บ่อน้ำร้อน', 'cospace'),
        ('ลานกิจกรรม', 'cospace'),
        ('อนุสาวรีย์', 'cospace'),
        ('โสต', 'cospace'),
        ('ศาลา', 'cospace'),
        ('ศาลพระ', 'cospace'),
        ('พระภูมิ', 'cospace'),
        ('กีฬา', 'cospace'),
        ('แยกขยะ', 'cospace'),
        ('สวนสาธารณะ', 'cospace'),
        ('รับรอง', 'cospace'),
        ('ชั้น', 'cospace'),
        ('สื่อสาร', 'otherworkspace'),
        ('เซลล์', 'otherworkspace'),
        ('ทบ.', 'otherworkspace'),
        ('ร้อย.', 'otherworkspace'),
        ('พัน.', 'otherworkspace'),
        ('จทบ', 'otherworkspace'),
        ('ทหาร', 'otherworkspace'),
        ('เอนกประสงค์', 'cospace'),
        ('สติ๊กเกอร์', 'cospace'),
        ('ลาบเป็ด', 'otherworkspace'),
        ('ส้มตำ', 'otherworkspace'),
        ('ร้าน', 'otherworkspace'),
        ('ตลาด', 'otherworkspace'),
        ('พาซ่า', 'otherworkspace'),
        ('วัตถุดิบ', 'otherworkspace'),
        ('แปลงเกษตร', 'otherworkspace'),
        ('งานอำนวย', 'otherworkspace'),
        ('ท่าเรือ', 'otherworkspace'),
        ('ท่ารถ', 'otherworkspace'),
        ('วินมอเตอร์', 'otherworkspace'),
        ('มูลนิธิ', 'otherworkspace'),
        ('การค้า', 'otherworkspace'),
        ('สำนัก', 'otherworkspace'),
        ('สนง.', 'otherworkspace'),
        ('สนง', 'otherworkspace'),
        ('ครัว', 'otherworkspace'),
        ('โรงลาบ', 'otherworkspace'),
        ('กลุ่มงาน', 'otherworkspace'),
        ('แผนงาน', 'otherworkspace'),
        ('ประชาสัมพันธ์', 'otherworkspace'),
        ('สวัสดิการ', 'otherworkspace'),
        ('สนับสนุน', 'otherworkspace'),
        ('ศูนย์สาธิต', 'otherworkspace'),
        ('ศูนย์บริการ', 'otherworkspace'),
        ('ประชาร่วมใจ', 'otherworkspace'),
        ('อำนวยการ', 'otherworkspace'),
        ('ศูนย์ช่วยเหลือ', 'otherworkspace'),
        ('สภา', 'otherworkspace'),
        ('ไร่', 'otherworkspace'),
        ('ป้อมตำรวจ', 'otherworkspace'),
        ('ป้อมเทศกิจ', 'otherworkspace'),
        ('ก่อสร้าง', 'otherworkspace'),
        ('จำกัด', 'otherworkspace'),
        ('มาร์ท', 'otherworkspace'),
        ('ประชานุกูล', 'otherworkspace'),
        ('สิรินธร', 'otherworkspace'),
        ('สำนักงาน', 'otherworkspace'),
        ('อาคารสถานที่', 'otherworkspace'),
        ('ที่ทำงาน', 'otherworkspace'),
        ('บริหาร', 'otherworkspace'),
        ('ธุระการ', 'otherworkspace'),
        ('ออฟฟิ', 'otherworkspace'),
        ('พาณิชย์', 'otherworkspace'),
        ('ผู้รับเหมา', 'otherworkspace'),
        ('โลจีสติก', 'otherworkspace'),
        ('จำกัด', 'otherworkspace'),
        ('บริษัท', 'otherworkspace'),
        ('โรงซ่อม', 'otherworkspace'),
        ('ซ่อมบำรุง', 'otherworkspace'),
        ('ศูนย์ซ่อม', 'otherworkspace'),
        ('สังฆภัณฑ์', 'otherworkspace'),
        ('สหกรณ์', 'otherworkspace'),
        ('ชมรม', 'otherworkspace'),
        ('แว่นท็อป', 'otherworkspace'),
        ('นวดแผน', 'otherworkspace'),
        ('ขายของ', 'otherworkspace'),
        ('บิวตี้', 'otherworkspace'),
        ('ส่งเสริม', 'otherworkspace'),
        ('ตัดผม', 'otherworkspace'),
        ('เสริมสวย', 'otherworkspace'),
        ('นามบัตร', 'otherworkspace'),
        ('ห้องเสื้อ', 'otherworkspace'),
        ('เซเว่น', 'otherworkspace'),
        ('โลตัส', 'otherworkspace'),
        ('คาร์แคร์', 'otherworkspace'),
        ('โทรทัศน์', 'otherworkspace'),
        ('ช่าง', 'otherworkspace'),
        ('ซัพพลาย', 'otherworkspace'),
        ('กองทุน', 'otherworkspace'),
        ('ปศุสัตว์', 'otherworkspace'),
        ('วิศวกรรม', 'otherworkspace'),
        ('ของเก่า', 'otherworkspace'),
        ('พัสดุ', 'otherworkspace'),
        ('ซักฟอก', 'otherworkspace'),
        ('ซักฝอก', 'otherworkspace'),
        ('ซักผ้า', 'otherworkspace'),
        ('ครุภัณฑ์', 'otherworkspace'),
        ('ดีไซน์', 'otherworkspace'),
        ('โรงซัก', 'otherworkspace'),
        ('ขนส่ง', 'otherworkspace'),
        ('ปั๊มน้ำมัน', 'otherworkspace'),
        ('ปั้มน้ำมัน', 'otherworkspace'),
        ('ปั้มนํามัน', 'otherworkspace'),
        ('ไฮโดรลิก', 'otherworkspace'),
        ('ไฮโดรลิค', 'otherworkspace'),
        ('หม้อน้ำ', 'otherworkspace'),
        ('โช๊คอัพ', 'otherworkspace'),
        ('ห้องยาน', 'otherworkspace'),
        ('พาหนะ', 'otherworkspace'),
        ('ยานยนต์', 'otherworkspace'),
        ('เครื่องเสียง', 'otherworkspace'),
        ('ซักรีด', 'otherworkspace'),
        ('ทิ้งขยะ', 'otherworkspace'),
        ('จัดเก็บ', 'otherworkspace'),
        ('พักขยะ', 'otherworkspace'),
        ('เก็บขยะ', 'otherworkspace'),
        ('มูลฝอย', 'otherworkspace'),
        ('ธนาคาร', 'otherworkspace'),
        ('ประกันชีวิต', 'otherworkspace'),
        ('โมบาย', 'otherworkspace'),
        ('คาเฟ่', 'otherworkspace'),
        ('cafe', 'otherworkspace'),
        ('เตี๋ยว', 'otherworkspace'),
        ('ลิสซิ่ง', 'otherworkspace'),
        ('สมุนไพร', 'otherworkspace'),
        ('ของฝาก', 'otherworkspace'),
        ('มูลนิธิ', 'otherworkspace'),
        ('สถานี', 'otherworkspace'),
        ('ปฏิบัติงาน', 'otherworkspace'),
        ('ธุรการ', 'otherworkspace'),
        ('การเงิน', 'otherworkspace'),
        ('ยุทธศาสตร์', 'otherworkspace'),
        ('ปฏิบัติการ', 'otherworkspace'),
        ('ศรีนครินทร์', 'otherworkspace'),
        ('รัตนโกสินทร์', 'otherworkspace'),
        ('Tower', 'otherworkspace'),
        ('0 ปี', 'otherworkspace'),
        ('0ปี', 'otherworkspace'),
        ('เฉลิมพระ', 'otherworkspace'),
        ('ฝึกงาน', 'otherworkspace'),
        ('ล้างรถ', 'otherworkspace'),
        ('จุดรับส่ง', 'otherworkspace'),
        ('สถานีขนส่ง', 'otherworkspace'),
        ('บขส', 'otherworkspace'),
        ('ท่ารถ', 'otherworkspace'),
        ('ธกส', 'otherworkspace'),
        ('กีฟฟารีน', 'otherworkspace'),
        ('เซ็นเตอร์', 'otherworkspace'),
        ('พาณิช', 'otherworkspace'),
        ('โฮมเซ็นเตอร์', 'otherworkspace'),
        ('เรือนเพาะ', 'otherworkspace'),
        ('เพาะชำ', 'otherworkspace'),
        ('ห.จ.ก.', 'otherworkspace'),
        ('หจก.', 'otherworkspace'),
        ('พานิชย์', 'otherworkspace')
    ]

    # for p in pref:
    #     if(word.startswith(p[0])):
    #         print(p[1])
    
    def getCategory2(self, building):
        categories = {}
        result = []
        #search in corpus
        for p in BuildingClassify.corpus:
            if(p[0] in building):
                cat = categories.get(building.index(p[0]))
                if cat:
                    if len(cat[0]) < len(p[0]):
                        categories[building.index(p[0])] = p
                else:    
                    categories[building.index(p[0])] = p
                    
        #building classify 
        if len(categories) > 0:
            for c in sorted(categories.keys()):
                result.append({
                    "idx": c,
                    "match": categories[c][0],
                    "type": categories[c][1]
                })
#             print(result)
            #1 class return or first of match index is "person" or "assredd" 
            if len(result) == 1 or (result[0]["idx"] == 0 and result[0]["type"] in ["person", "address"]):
                return result[0]
            
            #>1 class process
            elif result[len(result)-1]["type"] == "hotel":
                return result[len(result)-1]
            else:
                b_class = False
                for c in result:
                    if not b_class:
                        if c["match"] not in ["person", "address"]:
                            b_class = c
                        elif c["idx"] != 0:
                            b_class = c
                    elif c["match"] not in b_class["match"]:
                        if b_class["type"] in ["otherworkspace", "cospace"] and c["type"] not in ["person", "address"]:
                            if c["type"] in ["otherworkspace", "cospace", "habitat"]:
                                if b_class["type"] == "cospace" and c["type"] == "otherworkspace":
                                    b_class = c   
    #                             elif c["idx"] < b_class["idx"]:
    #                                 b_class = c                       
                            else:
                                b_class = c  
#                         elif c["type"] not in ["person", "address" , "habitat", "otherworkspace", "cospace"]:
#                             b_class = c  
                return b_class
                    
                    
        else: return False
                
    
    def getCategory(self, building):
        main_class = False
        main_index = 9000
        sub_class = False
        sub_index = 9000
        for p in BuildingClassify.corpus:
            if(p[0] in building):
                if p[1] == "person":
                    if building.index(p[0]) == 0:
                        main_class = p
                        main_index = building.index(p[0])
                elif p[1] == "cospace":
                    if building.index(p[0]) < sub_index:
                        sub_class = p
                        sub_index = building.index(p[0])
                    elif building.index(p[0]) == sub_index:
                        if len(p[0]) > len(sub_class[0]):
                            sub_class = p
                            sub_index = building.index(p[0])
                        
                        
                elif main_class:
#                         if building.index(p[0]) < main_index:
#                             main_class = p
#                             main_index = building.index(p[0])
#                         el
#                         if building.index(p[0]) > main_index:
                        if main_class[1] == "otherworkspace":
                                main_class = p
                                main_index = building.index(p[0])
                        elif building.index(p[0]) < main_index and p[1] != "otherworkspace":
                            main_class = p
                            main_index = building.index(p[0])
                        elif building.index(p[0]) == main_index:
                            if len(p[0]) > len(main_class[0]):
                                main_class = p
                                main_index = building.index(p[0])
                else:
                    main_class = p
                    main_index = building.index(p[0])
                    

        if main_class:
            return main_class
        else:
            return sub_class
                    
        

#     def getCategory(self, building):
# #         regex = re.compile("[" + building + "]*")
#         b_class = False
#         index = 9000
#         max_match = 0
        
#         for p in BuildingClassify.corpus:
#             if(p[0] in building):
                
#                 if building.index(p[0]) < index:
#                     b_class = p
#                     index = building.index(p[0])
#                     max_match = len(p[0])
#                 elif building.index(p[0]) == index:
#                     if len(p[0]) > max_match:
#                         b_class = p
#                         index = building.index(p[0])
#                         max_match = len(p[0])
#         return b_class

                    
        
        



